### ISSUE TITLE
Move CID spec to specs repo

### ISSUE THREAD

**Issue by mikeal** [multiformats/cid#24]
As part of my spec repo refactor I included a copy of the current CID spec.

https://github.com/ipld/specs/pull/72/files

However, before that lands I think we need to discuss moving the spec to that repo. There's obviously a lot of history in this repo discussing the spec, but it would also be nice to consolidate IPLD spec conversations and RFCs.

**Comment by vmx** [comment]
Sounds like this is an outdated issue. I propose closing it.
