### ISSUE TITLE
Comparison and relationship with W3C DID standard

### ISSUE THREAD

**Issue by nazar-pc** [multiformats/cid#48]
It is a bit annoying that neither DID spec mentions CID in any way nor CID recognized DID existence.

Would be nice to have something that describes similarities and differences between the two to make it easier for developer to make a decision on which one to use (or both) for a particular use case.

There is CID mention in https://did-ipid.github.io/ipid-did-method/ draft, but it is a draft and it is old.

**Comment by Stebalien** [comment]
Well, the CID spec doesn't mention the DID spec because they're unrelated and were developed independently. CIDs are for identifying content, DIDs are for identifying "entities" (usually people).

**Comment by nazar-pc** [comment]
https://www.w3.org/TR/did-core/:
> A DID refers to any subject (e.g., a person, organization, thing, data model, abstract entity, etc.) as determined by the controller of the DID.

I think there is some overlap between the two.

**Comment by Stebalien** [comment]
Well, not really:

1. CIDs identify immutable, structured, self-describing data without relying on any authorities.
2. DIDs name (usually mutably) conceptual "things" and have "controllers" (the party that decides what the "thing" is).

But you're right in that:

1. Their names are close.
2. They're both a part of "web3".

So I wouldn't say no if you wanted to add a new question to the FAQ (https://github.com/multiformats/cid#faq).
