### ISSUE TITLE
Add types to appease mypy!

### ISSUE THREAD

**Issue by bh2smith** [multiformats/cid#56]
Mypy complains and I have to silence it like this (which is not ideal).

```
from multiformats_cid import from_bytes  # type: ignore
```

If the project is already typed, then it should be as easy as adding an empty file called `py.typed` to the base module.

and adding this to setup configuration:

```
[options.package_data]
<YOUR_SRC_DIR> = py.typed
```

However, I went looking for the code [here](https://github.com/multiformats/cid) and I don't see any:

![Screenshot 2022-11-17 at 12 12 34](https://user-images.githubusercontent.com/11778116/202431735-ea18844d-6e92-4a8c-be43-5c7d965cc1e0.png)

**Comment by bh2smith** [comment]
From what I can tell, there is only one file in this project (although it doesn't appear to be here).

<img width="181" alt="Screenshot 2022-11-17 at 12 19 42" src="https://user-images.githubusercontent.com/11778116/202433054-9ff3dc42-7b7e-4ffd-8bf7-c1d9a0103e64.png">

If someone could link me to it I can add the types.

**Comment by rvagg** [comment]
Seems like you've found the right place to post this.
